---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-multitenancy-codereliant-io-v1-tenant
  failurePolicy: Fail
  name: vtenant.kb.io
  rules:
  - apiGroups:
    - multitenancy.codereliant.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tenants
  sideEffects: None
