apiVersion: multitenancy.codereliant.io/v1
kind: Tenant
metadata:
  name: tenant-sample
spec:
  adminEmail: admin@yourdomain.com
  adminGroups:
    - tenant-sample-admins
  userGroups:
    - tenant-sample-users
    - another-group-users
  namespaces:
    - tenant-sample-ns1
    - tenant-sample-ns2
    - tenant-sample-ns3
